import { SVGProps } from 'react'

export interface IconProps extends SVGProps<SVGSVGElement> {}

export {default as GoogleGridDotsIcon} from './custom/google-grid-dots'
export {default as SearchIcon} from './custom/search'
export {default as MicIcon} from './custom/mic'
export {default as ConfusedEmojiIcon} from './custom/confused-emoji'
export {default as SunnyIcon} from './custom/sunny'
export {default as CloudyIcon} from './custom/cloudy'
export {default as MoonIcon} from './custom/moon'
export {default as FrostIcon} from './custom/frost'
export {default as CloudySunnyIcon} from './custom/cloudy-sunny'
export {default as CloudySunnyLittleRainIcon} from './custom/cloudy-sunny-litlle-rain'
export {default as CloudySunnyModerateRainIcon} from './custom/cloudy-sunny-moderate-rain'
export {default as CloudyMoonIcon} from './custom/cloudy-moon'
export {default as CloudyMoonLittleRainIcon} from './custom/cloudy-moon-little-rain'
export {default as CloudyMoonModerateRainIcon} from './custom/cloudy-moon-moderate-rain'
export {default as CloudyHeavyRainIcon} from './custom/cloudy-heavy-rain'
export {default as FrostyRainIcon} from './custom/frosty-rain'
export {default as WindIcon} from './custom/wind'