import type { Metadata } from "next";
import { Roboto, Roboto_Flex } from "next/font/google";
import ThemeWrapper from "@/components/Wrappers/ThemeWrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const roboto = Roboto({weight:["400","500","700"],subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeWrapper>
          <Navbar/>
          <main className="min-h-[calc(100vh-4.05rem)]">
          {children}
          </main>
          <Footer/>
          </ThemeWrapper>
      </body>
    </html>
  );
}
